; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
upload_port = COM11
monitor_port = COM11
monitor_speed = 9600
lib_deps = 
	sensirion/Sensirion Core@^0.7.3
	sensirion/Sensirion I2C SCD4x@^1.1.0
	sandeepmistry/LoRa@^0.8.0
	4-20ma/ModbusMaster@^2.0.1
	sparkfun/SparkFun TSL2561@^1.1.0
